spring:
  application:
    name: problem4
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:library
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info